more updates my man

diff --git a/scripts/.local/bin/zentr b/scripts/.local/bin/zentr
--- a/scripts/.local/bin/zentr
+++ b/scripts/.local/bin/zentr
@@ -1,5 +1,14 @@
 #!/usr/bin/env bash
 
+dependencies=(entr find)
+
+for cmd in "${dependencies[@]}"; do
+    if ! command -v "$cmd" &> /dev/null; then
+        echo "Error: $cmd is not installed." >&2
+        exit 1
+    fi
+done
+
 function list_files() {
     # all but .git directory
     find . -not -path '*/\.git/*'
